# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_DRM_MSTAR)		+= mstar_drv.o \
				   mstar_gop.o \
				   mstar_mop.o \
				   mstar_pnl.o \
				   mstar_framebuffer.o \
				   mstar_dsi.o \
				   mstar_op2.o \
				   mstar_top.o
