# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_DTB_MST_MSD7816_TEST)	+= msd7816-test.dtb
dtb-$(CONFIG_DTB_MST_MSD309PX_TEST)	+= msd309px-test.dtb

obj-$(CONFIG_BUILTIN_DTB)	+= $(addsuffix .o, $(dtb-y))
