/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef INCLUDE_SOC_MSTAR_PMSLEEP_H_
#define INCLUDE_SOC_MSTAR_PMSLEEP_H_

#define MSTAR_PMSLEEP_WAKEUPSOURCE		0x20
#define MSTAR_PMSLEEP_WAKEUPSOURCE_RTC		BIT(4)
#define MSTAR_PMSLEEP_REG24			0x24
#define MSTAR_PMSLEEP_REG24_POWEROFF		BIT(15)
#define MSTAR_PMSLEEP_PMLOCK			0x48
#define MSTAR_PMSLEEP_PMLOCK_UNLOCK		0xbabe
#define MSTAR_PMSLEEP_REG70			0x70
#define MSTAR_PMSLEEP_REG70_ISOEN2GPIO4		BIT(3)
#define MSTAR_PMSLEEP_REG70_LINKWKINT2GPIO4	BIT(2)
#define MSTAR_PMSLEEP_REGC8			0xc8
#define MSTAR_PMSLEEP_REGC8_MAGIC		0x9f8e
#define MSTAR_PMSLEEP_REGCC			0xcc
#define MSTAR_PMSLEEP_REGCC_MAGIC		0x9f8e

#endif
