# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mstar specific clk
#

obj-$(CONFIG_MSTAR_MSC313_MPLL) += clk-msc313-mpll.o
obj-$(CONFIG_MSTAR_MSC313_CPUPLL) += clk-msc313-cpupll.o
obj-y += clk-msc313-pll-gater.o
	 clk-mstar-mux.o
	 clk-mstar_clkgen-gates.o
