# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mstar specific clk
#

obj-$(CONFIG_MSTAR_MSC313_MPLL) += clk-msc313-mpll.o
obj-$(CONFIG_MSTAR_MSC313_CPUPLL) += clk-msc313-cpupll.o
obj-$(CONFIG_MSTAR_MSC313_UPLL) += clk-msc313-upll.o
obj-$(CONFIG_MSTAR_MSC313_LPLL) += clk-msc313-lpll.o
obj-$(CONFIG_MSTAR_MSC313_MIUPLL) += clk-msc313-miupll.o
obj-y += clk-mstar-pll_common.o \
	 clk-msc313-mux.o
