# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mstar specific clk
#

obj-$(CONFIG_MSTAR_MSC313_MPLL) += clk-msc313-mpll.o
obj-y += clk-msc313-pll-gater.o \
	 clk-mstar-mux.o \
	 clk-mstar_clkgen-gates.o \
	 clk-mstar-upll.o \
	 clk-mstar_lpll.o \
	 clk-mstar_miupll.o \
	 clk-mstar-pll_common.o
