# SPDX-License-Identifier: GPL-2.0

mstar-pioneer3-ssd210-perdita-rescue-dtbs := mstar-pioneer3-ssd210-perdita.dtb \
						mstar-pioneer3-ssd210-perdita-usbotg.dtbo \
						mstar-pioneer3-ssd210-perdita-ili9341.dtbo

mstar-infinity2m-ssd202d-100ask-dongshanpione-overlay-dtbs := mstar-infinity2m-ssd202d-100ask-dongshanpione-carrier.dtb \
								mstar-infinity2m-ssd202d-100ask-dongshanpione-100ask_lcd0.dtbo \
								mstar-infinity2m-ssd202d-100ask-dongshanpione-ili9341.dtbo

#        mstar-pioneer3-ssd210-perdita-ili9341.dtbo \
#        mstar-pioneer3-ssd210-perdita-usbotg.dtbo \


dtb-$(CONFIG_ARCH_MSTARV7) += \
        mstar-infinity-msc313-breadbee_crust.dtb \
        mstar-infinity2m-ssd201-wirelesstag-ido-som2d01.dtb \
        mstar-infinity2m-ssd202d-100ask-dongshanpione.dtb \
        mstar-infinity2m-ssd202d-100ask-dongshanpione-carrier.dtb \
	mstar-infinity2m-ssd202d-100ask-dongshanpione-overlay.dtb \
        mstar-infinity2m-ssd202d-gw302.dtb \
        mstar-infinity2m-ssd202d-miyoo-mini.dtb \
        mstar-infinity2m-ssd202d-wirelesstag-ido-sbc2d06-v1b-22w.dtb \
        mstar-infinity2m-ssd202d-wirelesstag-ido-som2d01.dtb \
        mstar-infinity2m-ssd202d-sbc2d70.dtb \
        mstar-infinity2m-ssd202d-sbc2d86.dtb \
        mstar-infinity2m-ssd202d-ssd201htv2.dtb \
        mstar-infinity2m-ssd202d-unitv2.dtb \
        mstar-infinity2m-ssd202d-iht34.dtb \
        mstar-infinity2m-ssd203d-n1pro.dtb \
        mstar-infinity2m-ssr621d-tlnvr.dtb \
        mstar-infinity3-msc313e-breadbee.dtb \
        mstar-infinity3-msc313e-wiibee.dtb \
        mstar-infinity3-msc313d-mc400l.dtb \
        mstar-infinity6b0-ssc337de-mcf50.dtb \
        mstar-mercury5-ssc8336-mirrorcam.dtb \
        mstar-mercury5-ssc8336n-midrived06.dtb \
        mstar-mercury5-ssc8336n-midrived08.dtb \
        mstar-pioneer3-ssd210-kiipii.dtb \
        mstar-pioneer3-ssd210-perdita.dtb \
	mstar-pioneer3-ssd210-perdita-rescue.dtb \
        mstar-pioneer3-ssd210-100ask-dongshanpipicow.dtb \
        mstar-pioneer3-ssd210-100ask-dongshanpipicow-snander.dtb \
        mstar-pioneer3-ssd210-100ask-dongshanpipicow-devkitf.dtb \
        mstar-pioneer3-ssd210-qfn68demo.dtb \
        mstar-pioneer3-ssd212-sv50pd.dtb
