# SPDX-License-Identifier: GPL-2.0
subdir-y += actions
subdir-y += airoha
subdir-y += allwinner
subdir-y += alphascale
subdir-y += amazon
subdir-y += amlogic
subdir-y += arm
subdir-y += aspeed
subdir-y += axis
subdir-y += broadcom
subdir-y += calxeda
subdir-y += cirrus
subdir-y += cnxt
subdir-y += gemini
subdir-y += hisilicon
subdir-y += hpe
subdir-y += intel
subdir-y += marvell
subdir-y += mediatek
subdir-y += microchip
subdir-y += moxa
subdir-y += nspire
subdir-y += nuvoton
subdir-y += nvidia
subdir-y += nxp
subdir-y += qcom
subdir-y += realtek
subdir-y += renesas
subdir-y += rockchip
subdir-y += samsung
subdir-y += sigmastar
subdir-y += socionext
subdir-y += st
subdir-y += sunplus
subdir-y += synaptics
subdir-y += ti
subdir-y += unisoc
subdir-y += vt8500
subdir-y += xen
subdir-y += xilinx
dtb-$(CONFIG_ARCH_MSTARV7) += \
	mstar-infinity-msc313-breadbee_crust.dtb \
	mstar-infinity2m-ssd201-wirelesstag-ido-som2d01.dtb \
	mstar-infinity2m-ssd202d-100ask-dongshanpione.dtb \
	mstar-infinity2m-ssd202d-gw302.dtb \
	mstar-infinity2m-ssd202d-miyoo-mini.dtb \
	mstar-infinity2m-ssd202d-wirelesstag-ido-sbc2d06-v1b-22w.dtb \
	mstar-infinity2m-ssd202d-wirelesstag-ido-som2d01.dtb \
	mstar-infinity2m-ssd202d-sbc2d70.dtb \
	mstar-infinity2m-ssd202d-ssd201htv2.dtb \
	mstar-infinity2m-ssd202d-unitv2.dtb \
	mstar-infinity3-msc313e-breadbee.dtb \
	mstar-infinity3-msc313e-wiibee.dtb \
	mstar-infinity3-msc313d-mc400l.dtb \
	mstar-infinity6b0-ssc337de-mcf50.dtb \
	mstar-mercury5-ssc8336-mirrorcam.dtb \
	mstar-mercury5-ssc8336n-midrived06.dtb \
	mstar-mercury5-ssc8336n-midrived08.dtb \
	mstar-pioneer3-ssd210-kiipii.dtb
